function hash_(value) {return (typeof value==='string'?Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,value,Utilities.Charset.UTF_8):Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,value)).map(function(b){return ((b+256)%256).toString(16).padStart(2,'0');}).join('');}
function randomKey_(){return Utilities.getUuid().replace(/-/g,'')+Utilities.getUuid().replace(/-/g,'');}
function passwordDigest_(password){var p=PropertiesService.getScriptProperties(),salt=p.getProperty('PASSWORD_SALT');if(!salt){salt=randomKey_();p.setProperty('PASSWORD_SALT',salt);}return hash_(salt+':'+password);}
function equal_(a,b){a=String(a||'');b=String(b||'');var diff=a.length^b.length;for(var n=0;n<Math.max(a.length,b.length);n++)diff|=(a.charCodeAt(n)||0)^(b.charCodeAt(n)||0);return diff===0;}
function issueTicket_(){var key=randomKey_();CacheService.getScriptCache().put('ticket:'+hash_(key),'0',900);return key;}
function ticket_(key){if(typeof key!=='string'||!/^[a-f0-9]{64}$/.test(key))throw new Error('Sesi form berakhir. Muat sesi baru dan coba Kirim lagi.');var cache=CacheService.getScriptCache(),name='ticket:'+hash_(key),count=cache.get(name);if(count===null||Number(count)>=20)throw new Error('Sesi form berakhir. Muat sesi baru dan coba Kirim lagi.');cache.put(name,String(Number(count)+1),900);}
function technician_(pin){var expected=PropertiesService.getScriptProperties().getProperty('TECHNICIAN_PIN_HASH');if(expected&&!equal_(expected,passwordDigest_(String(pin||''))))throw new Error('PIN teknisi tidak sesuai.');}
function admin_(token){if(typeof token!=='string'||!/^[a-f0-9]{64}$/.test(token)||!CacheService.getScriptCache().get('admin:'+hash_(token)))throw new Error('Sesi admin berakhir. Silakan masuk kembali.');}
function loginAdmin(request){return rpc_(function(){request=request||{};ticket_(request.ticket);var cache=CacheService.getScriptCache(),failures=Number(cache.get('admin-failures')||'0');if(failures>=20)throw new Error('Terlalu banyak percobaan. Coba kembali dalam 10 menit.');var expected=PropertiesService.getScriptProperties().getProperty('ADMIN_PASSWORD_HASH');if(!expected||!equal_(expected,passwordDigest_(String(request.password||'')))){cache.put('admin-failures',String(failures+1),600);throw new Error('Password admin tidak sesuai atau admin belum dikonfigurasi.');}cache.remove('admin-failures');var token=randomKey_();cache.put('admin:'+hash_(token),'1',config_().adminSessionSeconds);return {ok:true,token:token};});}
function logoutAdmin(request){return rpc_(function(){admin_(request.token);CacheService.getScriptCache().remove('admin:'+hash_(request.token));return {ok:true};});}
