import {test} from 'node:test';import assert from 'node:assert/strict';import {runtime,request} from './helpers.mjs';
test('Drive commit survives retry without duplicate folders',()=>{const r=runtime(),c=r.context,p=request(c);const first=c.saveInspection(p);assert.equal(first.ok,true);assert.equal(c.saveInspection(p).duplicate,true);assert.equal(r.folders.get('1doqkhGxYICXQJeRpLmtyc1mZl5olgMzt').children.length,1);p.answers.Technician_Name='Different';assert.equal(c.saveInspection(p).ok,false);});
test('partial save stays out of history and retry completes same folder',()=>{const r=runtime(),c=r.context;presetAdmin(r);const auth=c.loginAdmin({password:'long-test-password',ticket:c.getBootstrap().ticket});const p=request(c);r.failOn('inspection.json');assert.equal(c.saveInspection(p).ok,false);assert.equal(c.listInspections({token:auth.token,type:'RTS'}).items.length,0);assert.equal(c.saveInspection(p).ok,true);assert.equal(c.listInspections({token:auth.token,type:'RTS'}).items.length,1);});
test('own receipt key is required and admin history requires authenticated session',()=>{const r=runtime(),c=r.context,p=request(c);c.saveInspection(p);assert.equal(c.getInspection({type:p.type,id:p.id,key:'wrong'}).ok,false);assert.equal(c.getInspection({type:p.type,id:p.id,key:p.receiptKey}).ok,true);assert.equal(c.listInspections({type:'RTS',token:'wrong'}).ok,false);});
test('photo validates signature before write, then only report holder can fetch it',()=>{const r=runtime(),c=r.context,p=request(c);p.answers.RTS_Instrument_Section_Status='Diperiksa';c.schema_('RTS').fields.filter(f=>f.prefix==='RTS_Instrument'&&f.type==='Enum'&&f.options.includes('Baik')).forEach(f=>p.answers[f.name]='Baik');p.photos=[{field:'RTS_Instrument_Image',type:'image/jpeg',data:Buffer.from([255,216,255,224,0,1]).toString('base64')}];const saved=c.saveInspection(p);assert.equal(saved.ok,true);assert.equal(c.getInspectionPhoto({type:p.type,id:p.id,field:p.photos[0].field,key:'bad'}).ok,false);assert.equal(c.getInspectionPhoto({type:p.type,id:p.id,field:p.photos[0].field,key:p.receiptKey}).ok,true);const bad=request(c);bad.photos=[{field:'Findings_Image',type:'image/jpeg',data:Buffer.from('<script>bad</script>').toString('base64')}];assert.equal(c.saveInspection(bad).ok,false);});
test('expired tickets, optional technician PIN and admin password failures are rejected',()=>{const r=runtime(),c=r.context,p=request(c);p.ticket='invalid';assert.equal(c.saveInspection(p).ok,false);r.props.set('TECHNICIAN_PIN_HASH',c.passwordDigest_('123456'));p.ticket=c.getBootstrap().ticket;assert.equal(c.saveInspection(p).ok,false);p.pin='123456';assert.equal(c.saveInspection(p).ok,true);presetAdmin(r);assert.equal(c.loginAdmin({password:'wrong',ticket:c.getBootstrap().ticket}).ok,false);});
function presetAdmin(r){r.props.set('ADMIN_PASSWORD_HASH',r.context.passwordDigest_('long-test-password'));}
test('tampered Drive manifest cannot read files outside its own report folder',()=>{const r=runtime(),c=r.context,p=request(c);p.photos=[{field:'Findings_Image',type:'image/jpeg',data:Buffer.from([255,216,255,224]).toString('base64')}];assert.equal(c.saveInspection(p).ok,true);const folder=r.folders.get('1doqkhGxYICXQJeRpLmtyc1mZl5olgMzt').getFoldersByName(p.id).next();const file=folder.getFilesByName('inspection.json').next(),record=JSON.parse(file.getBlob().getDataAsString());const external=r.folders.get('1JoaN3UkwcEGNGo0awHsOdQgkWfvLi6hJ').createFile(c.Utilities.newBlob([255,216,255,224,99],'image/jpeg','private.jpg'));record.photos.Findings_Image.id=external.getId();file.setContent(JSON.stringify(record));assert.equal(c.getInspectionPhoto({type:p.type,id:p.id,field:'Findings_Image',key:p.receiptKey}).ok,false);});
test('free text does not produce a false condition in history',()=>{const r=runtime(),p=request(r.context);p.answers.Technician_Name='Ada masalah';p.answers.Findings_Description='Tidak diperiksa';const checked=r.context.validate_('RTS',p.answers,[]);assert.equal(r.context.summary_({type:'RTS',answers:checked.answers}).status,'Tidak ada masalah dilaporkan');});
test('history continuation visits remaining committed records without duplicate IDs',()=>{const r=runtime(),c=r.context;presetAdmin(r);const auth=c.loginAdmin({password:'long-test-password',ticket:c.getBootstrap().ticket});for(let i=0;i<35;i++)assert.equal(c.saveInspection(request(c)).ok,true);const first=c.listInspections({token:auth.token,type:'RTS'});assert.equal(first.items.length,30);assert.ok(first.nextCursor);const second=c.listInspections({token:auth.token,type:'RTS',cursor:first.nextCursor});assert.equal(second.items.length,5);assert.equal(new Set([...first.items,...second.items].map(i=>i.id)).size,35);});
