import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import vm from 'node:vm';
function client(){const fakeNode={classList:{toggle(){},remove(){}},textContent:'',hidden:false,innerHTML:'',querySelectorAll:()=>[],querySelector:()=>null};const c=vm.createContext({console,Promise,JSON,Date,Set,Map,Math,Number,String,Object,Array,RegExp,Error,Blob,TextEncoder,Uint8Array,URL:{createObjectURL:()=>'',revokeObjectURL(){}},crypto:globalThis.crypto,atob,document:{querySelector:()=>fakeNode,querySelectorAll:()=>[],createElement:()=>fakeNode},sessionStorage:{getItem:()=>null,setItem(){},removeItem(){}},setTimeout(){},CSS:{escape:x=>x},window:{scrollTo(){}},google:{script:{run:{withSuccessHandler:()=>({withFailureHandler:()=>new Proxy({},{get:()=>()=>{}})})}}}});
 const source=readFileSync(new URL('../appsscript/Client.html',import.meta.url),'utf8').replace(/^<script>\n/,'').replace(/<\/script>\s*$/,'');vm.runInContext(source,c);vm.runInContext('globalThis.s=state;renderForm=()=>{};saveDraft=()=>{};success=()=>{globalThis.recovered=true};selected=()=>{};toast=()=>{};',c);return c;}
test('unknown committed submission is recovered from draft key before requiring new photos',async()=>{const c=client();c.s.type='RTS';c.s.id='same-id';c.s.key='same-key';c.s.saved=null;c.s.bootstrap={schemas:{RTS:{}}};c.response={ok:true,record:{id:'same-id',type:'RTS',savedAt:'now',photos:[]}};vm.runInContext('rpc=async(name,auth)=>{if(name!=="getInspection"||auth.id!=="same-id"||auth.key!=="same-key")throw Error("wrong request");return response;};',c);await c.recoverDraft();assert.equal(c.recovered,true);assert.equal(c.s.saved.id,'same-id');assert.equal(c.s.busy,false);});
test('busy or photo processing prevents switching inspection type',()=>{const c=client();c.s.type='RADAR';c.s.busy=true;c.choose('RTS');assert.equal(c.s.type,'RADAR');c.s.busy=false;c.s.processing=true;c.choose('RTS');assert.equal(c.s.type,'RADAR');});
test('ZIP uses one immutable report credential even if another report opens during download',async()=>{const c=client();c.s.reportAuth={id:'first',type:'RTS',token:'admin'};c.s.report={csv:'header\r\nfirst\r\n',record:{id:'first',type:'RTS',photos:[{field:'one'},{field:'two'}]}};c.calls=[];vm.runInContext('rpc=async(name,auth)=>{calls.push(auth.id);state.reportAuth={id:"second",type:"RTS",token:"admin"};return {name:auth.field+".jpg",data:"/9j/",type:"image/jpeg"};};zipFiles=()=>new Blob([]);downloadBlob=()=>{};',c);await c.downloadZip();assert.deepEqual(Array.from(c.calls),['first','first']);});
test('save error unfreezes form before rendering fields and PIN for correction',async()=>{const c=client();c.s.type='RTS';c.s.bootstrap={schemas:{RTS:{fields:[]}},limits:{total:8000000}};vm.runInContext('renderForm=()=>{globalThis.lastRenderBusy=state.busy};rpc=async(name)=>{if(name==="getBootstrap")return {ticket:"ticket"};throw Error("PIN incorrect");};',c);await c.submit();assert.equal(c.lastRenderBusy,false);});
test('known saved report retains its own authorization when initial read fails',async()=>{const c=client();c.s.id='saved-id';c.s.type='RTS';c.s.key='own-key';vm.runInContext('rpc=async()=>{throw Error("temporary outage")};',c);await c.loadOwnReport();assert.equal(c.s.reportAuth.id,'saved-id');assert.equal(c.s.reportAuth.key,'own-key');});
test('uncached report read retries RPC rather than dereferencing an absent record',async()=>{const c=client();c.s.report=null;c.s.reportAuth=null;vm.runInContext('rpc=async()=>{globalThis.didRetry=true;throw Error("report authorization unavailable")};',c);await assert.rejects(c.reportReady(),/report authorization unavailable/);assert.equal(c.didRetry,true);});
test('printing aborts when a report photograph cannot decode',async()=>{const c=client();c.s.reportAuth={id:'first',type:'RTS'};vm.runInContext('loadAllPhotos=async()=>true;document.querySelectorAll=()=>[{decode:async()=>{throw Error("invalid image")}}];window.print=()=>{globalThis.printed=true};toast=message=>{globalThis.toastMessage=message};',c);await c.printReport();assert.notEqual(c.printed,true);assert.match(c.toastMessage,/belum dapat dicetak/);});
test('printing aborts if report changes while photograph decoding is in progress',async()=>{const c=client();c.s.reportAuth={id:'first',type:'RTS'};vm.runInContext('loadAllPhotos=async()=>true;document.querySelectorAll=()=>[{decode:async()=>{state.reportAuth={id:"second",type:"RTS"}}}];window.print=()=>{globalThis.printed=true};',c);await c.printReport();assert.notEqual(c.printed,true);});
