import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const ctx=vm.createContext({console,JSON,Date,Set,Map,Math,Number,String,Object,Array,RegExp});
for(const file of ['Schema.gs','Validation.gs'])vm.runInContext(readFileSync(new URL('../appsscript/'+file,import.meta.url),'utf8'),ctx);
const schema=type=>ctx.schema_(type);
const valid=type=>{const a={Inspection_DateTime:'2026-10-04T11:30',Technician_Name:'Teknisi',Radar_ID:'H-29',Radar_Location:'Area A',RTS_ID:'TM60-01',RTS_Location:'Area B'};for(const f of schema(type).fields.filter(f=>f.name.endsWith('_Section_Status')))a[f.name]='Tidak berlaku (N/A)';return a;};
test('Radar and RTS require identity and section status',()=>{for(const type of ['RADAR','RTS'])assert.equal(ctx.validate_(type,valid(type),[]).errors.length,0);assert.ok(ctx.validate_('RTS',{},[]).errors.length>5);});
test('RTS checked instrument requires nivo, cleaning and photograph',()=>{const a=valid('RTS');a.RTS_Instrument_Section_Status='Diperiksa';const result=ctx.validate_('RTS',a,[]);for(const name of ['RTS_Instrument_Nivo','RTS_Instrument_Cleanliness','RTS_Instrument_Image'])assert.ok(result.errors.some(e=>e.field===name));});
test('Radar checked general requires component answers even with a photo',()=>{const a=valid('RADAR');a.General_Section_Status='Diperiksa';assert.ok(ctx.validate_('RADAR',a,['General_Image']).errors.some(e=>e.field==='General_Scanner'));});
test('N/A clears hidden stale faults and readings',()=>{const a=valid('RADAR');a.General_Scanner='Ada masalah';a.General_Battery_Voltage='NaN';const r=ctx.validate_('RADAR',a,[]);assert.equal(r.errors.length,0);assert.equal(r.answers.General_Scanner,'');});
test('not inspected and actual problems require explanation',()=>{const a=valid('RTS');a.RTS_Panel_Section_Status='Tidak diperiksa';assert.ok(ctx.validate_('RTS',a,[]).errors.some(e=>e.field==='RTS_Panel_Notes'));a.RTS_Panel_Notes='Akses panel belum tersedia';assert.equal(ctx.validate_('RTS',a,[]).errors.length,0);});
test('reject malformed dates, invalid choices and non-finite numeric readings',()=>{const a=valid('RTS');a.Inspection_DateTime='2026-02-30T12:00';a.RTS_Power_Section_Status='Diperiksa';a.RTS_Power_Battery_Voltage='Infinity';const r=ctx.validate_('RTS',a,[]);assert.ok(r.errors.some(e=>e.field==='Inspection_DateTime'));assert.ok(r.errors.some(e=>e.field==='RTS_Power_Battery_Voltage'));a.RTS_Power_Section_Status='fake';assert.ok(ctx.validate_('RTS',a,[]).errors.some(e=>e.field==='RTS_Power_Section_Status'));});
test('zero reading is valid and requires its display unit',()=>{const a=valid('RTS');a.RTS_Instrument_Section_Status='Diperiksa';a.RTS_Instrument_Tilt_X='0';const r=ctx.validate_('RTS',a,[]);assert.equal(r.answers.RTS_Instrument_Tilt_X,'0');assert.ok(r.errors.some(e=>e.field==='RTS_Instrument_Tilt_Unit'));});
test('CSV contains schema columns and neutralizes formulas',()=>{const csv=ctx.csv_('RTS',{Technician_Name:'=HYPERLINK("bad")',RTS_ID:'01',RTS_Location:'a,b'});assert.match(csv,/"'=HYPERLINK/);assert.match(csv,/"a,b"/);assert.equal(csv.split('\r\n')[0].split(',').length,schema('RTS').fields.length);});
test('bulk CSV preserves multiline notes and rejects mixed schemas',()=>{const first=ctx.csv_('RTS',{Findings_Description:'line one\r\nline two'}),second=ctx.csv_('RTS',{RTS_ID:'02'});assert.ok(ctx.csvJoin_([first,second]).includes('"line one\r\nline two"'));assert.throws(()=>ctx.csvJoin_([first,ctx.csv_('RADAR',{})]));});
const names=(type,prefix)=>Array.from(schema(type).fields.filter(f=>f.prefix===prefix).map(f=>f.name));
test('Radar sections show only the requested fields',()=>{
 assert.deepEqual(names('RADAR','Genset'),['Genset_Section_Status','Genset_Visual_Condition','Genset_Fuel_Level','Genset_Oil_Level','Genset_Number','Genset_Starter_Battery_Voltage_V','Genset_Notes','Genset_Image']);
 assert.deepEqual(names('RADAR','Controller'),['Controller_Section_Status','Controller_General_Condition','Controller_Laptop_Condition','Controller_Image']);
 assert.deepEqual(names('RADAR','Solar'),['Solar_Section_Status','Solar_Cleanliness','Solar_Cables_Connectors','Solar_Mounting','Solar_Image']);
 assert.deepEqual(names('RADAR','Weather'),['Weather_Section_Status','Weather_General_Condition','Weather_Image']);
 assert.deepEqual(names('RTS','RTS_Network'),['RTS_Network_Section_Status','RTS_Network_Moxa_Indicator','RTS_Network_Cables']);
 assert.ok(schema('RADAR').sections.includes('Weather sensor'));assert.ok(!schema('RADAR').sections.includes('Weather station'));
 for(const type of ['RADAR','RTS'])assert.ok(schema(type).fields.every(f=>f.type==='Show'||schema(type).sections.includes(f.section)));
});
test('checked Genset needs its checks and photo; notes only when something is wrong or skipped',()=>{const a=valid('RADAR');a.Genset_Section_Status='Diperiksa';let r=ctx.validate_('RADAR',a,[]);for(const n of ['Genset_Visual_Condition','Genset_Fuel_Level','Genset_Oil_Level','Genset_Image'])assert.ok(r.errors.some(e=>e.field===n),n);assert.ok(!r.errors.some(e=>e.field==='Genset_Notes'));Object.assign(a,{Genset_Visual_Condition:'Baik',Genset_Fuel_Level:'Ada masalah',Genset_Oil_Level:'Baik'});r=ctx.validate_('RADAR',a,['Genset_Image']);assert.ok(r.errors.some(e=>e.field==='Genset_Notes'));a.Genset_Notes='Solar tinggal seperempat';a.Findings_Description='Genset perlu isi bahan bakar';assert.equal(ctx.validate_('RADAR',a,['Genset_Image']).errors.length,0);});
test('sections without notes or photo fields do not demand them, but problems still need the findings summary',()=>{const a=valid('RADAR');a.Controller_Section_Status='Diperiksa';a.Controller_General_Condition='Ada masalah';a.Controller_Laptop_Condition='Tidak diperiksa';let r=ctx.validate_('RADAR',a,['Controller_Image']);assert.deepEqual(Array.from(r.errors.map(e=>e.field)),['Findings_Description']);a.Findings_Description='Controller bermasalah';assert.equal(ctx.validate_('RADAR',a,['Controller_Image']).errors.length,0);const t=valid('RTS');t.RTS_Network_Section_Status='Diperiksa';t.RTS_Network_Moxa_Indicator='Baik';t.RTS_Network_Cables='Baik';assert.equal(ctx.validate_('RTS',t,[]).errors.length,0);t.RTS_Network_Cables='';assert.deepEqual(Array.from(ctx.validate_('RTS',t,[]).errors.map(e=>e.field)),['RTS_Network_Cables']);});
test('extra radar options are accepted only for Radar_ID',()=>{const a=valid('RADAR');a.Radar_ID='H-31';assert.ok(ctx.validate_('RADAR',a,[]).errors.some(e=>e.field==='Radar_ID'));assert.equal(ctx.validate_('RADAR',a,[],{Radar_ID:['H-31']}).errors.length,0);a.Radar_Location='';a.General_Section_Status='Diperiksa';a.General_Scanner='Dibuat-buat';assert.ok(ctx.validate_('RADAR',a,[],{Radar_ID:['H-31'],General_Scanner:[]}).errors.some(e=>e.field==='General_Scanner'));});
test('historical weather readings use the renamed section without restoring form requirements',()=>{
 const a={...valid('RADAR'),Weather_Temperature_Value:'30',Weather_Notes:'Old sensor reading'};
 const report=ctx.reportSchema_('RADAR',a);
 assert.equal(report.fields.find(f=>f.name==='Weather_Temperature_Value').section,'Weather sensor');
 assert.equal(ctx.validate_('RADAR',a,[]).errors.length,0);
 assert.equal(Object.hasOwn(ctx.validate_('RADAR',a,[]).answers,'Weather_Temperature_Value'),false);
});
test('bulk report export retains removed readings and multiline notes alongside new checklist records',()=>{
 const records=[{type:'RADAR',answers:{Radar_ID:'H-29',Controller_Alarm:'Ada masalah',Controller_Notes:'first line\r\nsecond line'}},{type:'RADAR',answers:{Radar_ID:'H-31',Controller_General_Condition:'Baik',Controller_Laptop_Condition:'Baik'}}];
 const text=ctx.csvReports_('RADAR',records);
 assert.match(text,/Controller_Alarm/);assert.match(text,/"first line\r\nsecond line"/);assert.match(text,/"H-31"/);
 assert.equal((text.match(/Inspection_DateTime/g)||[]).length,1);
 assert.throws(()=>ctx.csvReports_('RADAR',[...records,{type:'RTS',answers:{}}]));
 assert.doesNotMatch(ctx.csvReports_('RADAR',[records[1]]),/Controller_Alarm/);
});
