import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {createInspectionService} from '../server/inspection.js';
import {schemas} from '../server/domain.js';

export function fakeDrive(){
 const files=new Map();let seq=0,failName='';
 const copy=f=>f&&({...f,parents:[...f.parents]});
 const drive={files,generateIds:async count=>Array.from({length:count},()=>`drive-id-${String(++seq).padStart(12,'0')}`),async get(id){if(!files.has(id)){const e=Error('Not found');e.status=404;throw e;}return copy(files.get(id));},async createFile({id,name,parent,mimeType,body}){await Promise.resolve();if(files.has(id)){const e=Error('Conflict');e.status=409;throw e;}if(name===failName){failName='';throw Error('Interrupted upload');}const bytes=Buffer.from(body||'');const f={id,name,parents:[parent],mimeType,size:String(bytes.length),body:bytes,capabilities:{canEdit:true},md5Checksum:createHash('md5').update(bytes).digest('hex')};files.set(id,f);return copy(f);},async download(id,limit){const f=await this.get(id);if(f.body.length>limit)throw Error('File too large');return Buffer.from(f.body);},async list({parent,name,mimeType,pageSize=30,pageToken}){const start=Number(pageToken||0);const all=[...files.values()].filter(f=>f.parents.includes(parent)&&(!name||f.name===name)&&(!mimeType||f.mimeType===mimeType));return {files:all.slice(start,start+pageSize).map(copy),nextPageToken:all.length>start+pageSize?String(start+pageSize):null};},failOn:name=>{failName=name;}};
 for(const [id,parent] of [['root-folder-01',''],['radar-folder-01','root-folder-01'],['rts-folder-01','root-folder-01']])files.set(id,{id,name:id,parents:parent?[parent]:[],mimeType:'application/vnd.google-apps.folder',capabilities:{canEdit:true},body:Buffer.alloc(0)});
 return drive;
}
export const testConfig={secret:'test-only-secret-that-is-at-least-32-characters',folderIds:{RADAR:'radar-folder-01',RTS:'rts-folder-01'},rootFolderId:'root-folder-01'};
const bytes=Buffer.from([255,216,255,224]);
export function payload(withPhoto=true){const answers={Inspection_DateTime:'2026-10-04T12:40',Technician_Name:'TEST ONLY',RTS_ID:'TM60-TEST',RTS_Location:'TEST'};for(const f of schemas.RTS.fields.filter(f=>f.name.endsWith('_Section_Status')))answers[f.name]='Tidak berlaku (N/A)';if(withPhoto){answers.RTS_Instrument_Section_Status='Diperiksa';for(const f of schemas.RTS.fields.filter(f=>f.prefix==='RTS_Instrument'&&f.type==='Enum'&&f.options.includes('Baik')))answers[f.name]='Baik';}return {type:'RTS',receiptKey:'a'.repeat(64),answers,photos:withPhoto?[{field:'RTS_Instrument_Image',type:'image/jpeg',size:bytes.length,digest:createHash('sha256').update(bytes).digest('hex')}]:[]};}
async function started(withPhoto=true){const drive=fakeDrive(),svc=createInspectionService({drive,config:testConfig}),p=payload(withPhoto),a=await svc.allocate(p);await svc.begin({...p,uploadTicket:a.uploadTicket});return {drive,svc,p,a};}
test('native Drive: preallocated IDs survive concurrent begin/photo/commit retries',async()=>{const {drive,svc,p,a}=await started();await Promise.all([svc.begin({...p,uploadTicket:a.uploadTicket}),svc.begin({...p,uploadTicket:a.uploadTicket})]);const photo={uploadTicket:a.uploadTicket,field:'RTS_Instrument_Image',type:'image/jpeg',data:bytes.toString('base64')};await Promise.all([svc.photo(photo),svc.photo(photo)]);const result=await Promise.all([svc.commit({uploadTicket:a.uploadTicket}),svc.commit({uploadTicket:a.uploadTicket})]);assert.equal(result[0].id,result[1].id);assert.equal([...drive.files.values()].filter(f=>f.name==='inspection.json').length,1);assert.equal([...drive.files.values()].filter(f=>f.name==='RTS_Instrument_Image.jpg').length,1);const own=await svc.read({type:'RTS',id:a.id,key:p.receiptKey});assert.equal(own.record.answers.Inspection_ID,a.id);assert.equal(own.record.answers.Technician_Name,'TEST ONLY');assert.equal(JSON.stringify(own).includes('receiptHash'),false);});
test('native Drive: partial transaction is excluded from history and retry completes',async()=>{const {drive,svc,a}=await started();assert.equal((await svc.list({type:'RTS'})).items.length,0);await assert.rejects(svc.commit({uploadTicket:a.uploadTicket}),/foto|Foto/);drive.failOn('RTS_Instrument_Image.jpg');const photo={uploadTicket:a.uploadTicket,field:'RTS_Instrument_Image',type:'image/jpeg',data:bytes.toString('base64')};await assert.rejects(svc.photo(photo),/Interrupted/);await svc.photo(photo);await svc.commit({uploadTicket:a.uploadTicket});assert.equal((await svc.list({type:'RTS'})).items.length,1);});
test('native Drive: changed retry, incorrect digest and forged ticket are rejected',async()=>{const {svc,p,a}=await started();await assert.rejects(svc.begin({...p,answers:{...p.answers,Technician_Name:'Changed'},uploadTicket:a.uploadTicket}),/berubah|sesuai/);await assert.rejects(svc.photo({uploadTicket:a.uploadTicket,field:'RTS_Instrument_Image',type:'image/jpeg',data:Buffer.from([255,216,255,1]).toString('base64')}),/sesuai|berubah/);await assert.rejects(svc.commit({uploadTicket:a.uploadTicket+'bad'}),/sesi|Sesi|tiket|Tiket/);});
test('native Drive: editing pending answers while preserving stored hashes is rejected',async()=>{const {drive,svc,a}=await started(false);const file=[...drive.files.values()].find(f=>f.name==='pending.json'),intent=JSON.parse(file.body);intent.answers.Technician_Name='Altered in Drive';file.body=Buffer.from(JSON.stringify(intent));await assert.rejects(svc.commit({uploadTicket:a.uploadTicket}),/berubah|sesuai/);assert.equal([...drive.files.values()].some(f=>f.name==='inspection.json'),false);});
test('native Drive: committed photos reject replacement within the same folder',async()=>{const {drive,svc,p,a}=await started();await svc.photo({uploadTicket:a.uploadTicket,field:'RTS_Instrument_Image',type:'image/jpeg',data:bytes.toString('base64')});await svc.commit({uploadTicket:a.uploadTicket});const photo=[...drive.files.values()].find(f=>f.name==='RTS_Instrument_Image.jpg');photo.body=Buffer.from([255,216,255,1]);await assert.rejects(svc.readPhoto({type:'RTS',id:a.id,key:p.receiptKey,field:'RTS_Instrument_Image'}),/sesuai|berubah/);});
test('native Drive: duplicate commit checks the stored record body, not copied hashes',async()=>{const {drive,svc,a}=await started(false);await svc.commit({uploadTicket:a.uploadTicket});const file=[...drive.files.values()].find(f=>f.name==='inspection.json'),record=JSON.parse(file.body);record.answers.Technician_Name='Altered record';file.body=Buffer.from(JSON.stringify(record));await assert.rejects(svc.commit({uploadTicket:a.uploadTicket}),/berbeda|berubah|sesuai/);});
test('native Drive: receipt and file parents constrain access even with edited manifest',async()=>{const {drive,svc,p,a}=await started();await svc.photo({uploadTicket:a.uploadTicket,field:'RTS_Instrument_Image',type:'image/jpeg',data:bytes.toString('base64')});await svc.commit({uploadTicket:a.uploadTicket});await assert.rejects(svc.read({type:'RTS',id:a.id,key:'b'.repeat(64)}),/Kunci/);const json=[...drive.files.values()].find(f=>f.name==='inspection.json'),r=JSON.parse(json.body);const target=drive.files.get(r.photos.RTS_Instrument_Image.id);target.parents=['root-folder-01'];await assert.rejects(svc.readPhoto({type:'RTS',id:a.id,key:p.receiptKey,field:'RTS_Instrument_Image'}),/folder/);});
test('native Drive: legacy UUID records remain readable; root escape rejected',async()=>{const drive=fakeDrive(),svc=createInspectionService({drive,config:testConfig});const id='550e8400-e29b-41d4-a716-446655440000';await drive.createFile({id:'legacy-folder-id',name:id,parent:testConfig.folderIds.RTS,mimeType:'application/vnd.google-apps.folder'});await drive.createFile({id:'legacy-json-id',name:'inspection.json',parent:'legacy-folder-id',mimeType:'application/json',body:JSON.stringify({schemaVersion:1,id,type:'RTS',model:'Leica TM60',answers:payload(false).answers,photos:{},savedAt:'2026-10-04T05:00:00Z',receiptHash:createHash('sha256').update('a'.repeat(64)).digest('hex')})});const r=await svc.read({type:'RTS',id,key:'a'.repeat(64)});assert.equal(r.record.id,id);await assert.rejects(svc.read({type:'RTS',id:testConfig.rootFolderId,key:'a'.repeat(64)}),/folder|Folder/);});
function radarPayload(radarId){const answers={Inspection_DateTime:'2026-10-04T12:40',Technician_Name:'TEST ONLY',Radar_ID:radarId,Radar_Location:'TEST'};for(const f of schemas.RADAR.fields.filter(f=>f.name.endsWith('_Section_Status')))answers[f.name]='Tidak berlaku (N/A)';return {type:'RADAR',receiptKey:'c'.repeat(64),answers,photos:[]};}
test('native Drive: new radar is registered once, listed for everyone and normalized',async()=>{const drive=fakeDrive(),svc=createInspectionService({drive,config:testConfig});assert.deepEqual((await svc.radars()).radars,[]);const added=await svc.addRadar({id:'  h-31 '});assert.equal(added.id,'H-31');assert.equal(added.existing,false);const again=await svc.addRadar({id:'H-31'});assert.equal(again.existing,true);assert.equal(again.id,'H-31');const builtin=await svc.addRadar({id:'h-29'});assert.equal(builtin.id,'H-29');assert.equal(builtin.existing,true);await svc.addRadar({id:'H-100'});await svc.addRadar({id:'H-9'});assert.deepEqual((await svc.radars()).radars,['H-9','H-31','H-100']);assert.equal([...drive.files.values()].filter(f=>f.name==='radar-registry-H-31.json').length,1);assert.equal((await svc.list({type:'RADAR'})).items.length,0);});
test('native Drive: radar IDs are validated before anything is written',async()=>{const drive=fakeDrive(),svc=createInspectionService({drive,config:testConfig}),before=drive.files.size;for(const bad of ['','X','a/b','H-29;DROP',"x'y",'<b>','A'.repeat(25),null])await assert.rejects(svc.addRadar({id:bad}),/ID radar/);assert.equal(drive.files.size,before);});
test('native Drive: inspection accepts a registered radar and rejects an unknown one',async()=>{const drive=fakeDrive(),svc=createInspectionService({drive,config:testConfig});await assert.rejects(svc.allocate(radarPayload('H-31')),/Lengkapi/);await svc.addRadar({id:'H-31'});const p=radarPayload('H-31'),a=await svc.allocate(p);await svc.begin({...p,uploadTicket:a.uploadTicket});await svc.commit({uploadTicket:a.uploadTicket});const listed=await svc.list({type:'RADAR'});assert.equal(listed.items.length,1);assert.equal(listed.items[0].unit,'H-31');const builtin=radarPayload('H-29');assert.ok((await svc.allocate(builtin)).id);});
test('native Drive: registry entries ignore foreign JSON files and cap the list',async()=>{const drive=fakeDrive(),svc=createInspectionService({drive,config:testConfig});await drive.createFile({id:'foreign-json-1',name:'notes.json',parent:testConfig.folderIds.RADAR,mimeType:'application/json',body:'{}'});await drive.createFile({id:'foreign-json-2',name:'radar-registry-lower-case.json',parent:testConfig.folderIds.RADAR,mimeType:'application/json',body:'{}'});assert.deepEqual((await svc.radars()).radars,[]);for(let i=0;i<100;i++)await drive.createFile({id:'seed-radar-'+String(i).padStart(3,'0'),name:'radar-registry-R'+i+'.json',parent:testConfig.folderIds.RADAR,mimeType:'application/json',body:'{}'});await assert.rejects(svc.addRadar({id:'R-NEW'}),/penuh/);});
