import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createRpcHandler} from '../server/rpc.js';
import {signToken,verifyToken} from '../server/auth.js';
import {GoogleDrive} from '../server/drive.js';
const config={secret:'server-only-secret-that-is-longer-than-32-characters',adminPassword:'test-admin-password-long',technicianPin:'',clientId:'dummy',clientSecret:'dummy',refreshToken:'dummy',origin:'https://weekly.test',production:true,folderIds:{RADAR:'radar-folder-01',RTS:'rts-folder-01'},rootFolderId:'root-folder-01',version:'2.0.0'};
async function call(handler,method,payload={},headers={}){const response={statusCode:200,headers:{},setHeader(k,v){this.headers[k.toLowerCase()]=v;},end(body){this.data=JSON.parse(body);}};await handler({method:'POST',headers:{origin:'https://weekly.test','content-type':'application/json',...headers},body:{method,payload}},response);return response;}
test('Vercel API: configuration missing stays explicit, bootstrap never exposes secrets',async()=>{const handler=createRpcHandler({config:{...config,clientId:'',refreshToken:''},drive:{}});const boot=await call(handler,'getBootstrap');assert.equal(boot.data.configuration.driveReady,false);assert.equal(boot.data.schemas.RTS.model,'Leica TM60');assert.equal(JSON.stringify(boot.data).includes(config.secret),false);const write=await call(handler,'allocateInspection',{ticket:boot.data.ticket});assert.equal(write.data.ok,false);assert.match(write.data.message,/Drive belum terhubung/);});
test('Vercel API: cross-origin mutation and private helper method are rejected',async()=>{const handler=createRpcHandler({config,drive:{}});const cross=await call(handler,'getBootstrap',{}, {origin:'https://attacker.test'});assert.equal(cross.statusCode,403);const helper=await call(handler,'setup_');assert.equal(helper.data.ok,false);});
test('Vercel API: admin cookie is required, login uses cookie and logout clears it',async()=>{const handler=createRpcHandler({config,drive:{}}),boot=await call(handler,'getBootstrap');const wrong=await call(handler,'loginAdmin',{password:'wrong',ticket:boot.data.ticket});assert.equal(wrong.data.ok,false);const login=await call(handler,'loginAdmin',{password:config.adminPassword,ticket:boot.data.ticket});assert.equal(login.data.token,'cookie');const cookie=login.headers['set-cookie'];assert.match(cookie,/HttpOnly/);assert.match(cookie,/Secure/);assert.match(cookie,/SameSite=Strict/);const forbidden=await call(handler,'listInspections',{type:'RTS',token:'invented'});assert.equal(forbidden.data.ok,false);const logout=await call(handler,'logoutAdmin',{}, {cookie:cookie.split(';')[0]});assert.equal(logout.data.ok,true);assert.match(logout.headers['set-cookie'],/Max-Age=0/);});
test('Vercel API: signed tickets reject tampering, expiration and wrong purpose',()=>{const ticket=signToken(config,'bootstrap');assert.equal(verifyToken(config,ticket,'bootstrap').purpose,'bootstrap');assert.throws(()=>verifyToken(config,ticket+'x','bootstrap'),/Sesi/);assert.throws(()=>verifyToken(config,ticket,'upload'),/Sesi/);assert.throws(()=>verifyToken(config,signToken(config,'bootstrap',{},-1),'bootstrap'),/Sesi/);});
test('Drive HTTP adapter creates folders with JSON metadata, not a media upload',async()=>{let seen;const drive=new GoogleDrive(config,async(url,init)=>{if(url.includes('oauth2.googleapis.com'))return new Response(JSON.stringify({access_token:'server-only-token',expires_in:3600}),{headers:{'content-type':'application/json'}});seen={url,init};return new Response(JSON.stringify({id:'allocated-id',name:'allocated-id',parents:['rts-root-01']}),{headers:{'content-type':'application/json'}});});await drive.createFile({id:'allocated-id',name:'allocated-id',parent:'rts-root-01',mimeType:'application/vnd.google-apps.folder'});assert.equal(seen.url.includes('/upload/'),false);assert.match(seen.init.headers['content-type'],/application\/json/);assert.equal(JSON.parse(seen.init.body).id,'allocated-id');});
