import {createHash,createHmac,randomBytes,scryptSync,timingSafeEqual} from 'node:crypto';
export const hash=v=>createHash('sha256').update(v).digest('hex');
export function equal(a,b){const x=Buffer.isBuffer(a)?a:Buffer.from(String(a||'')),y=Buffer.isBuffer(b)?b:Buffer.from(String(b||''));return x.length===y.length&&timingSafeEqual(x,y);}
export function signToken(config,purpose,data={},seconds=900){if(config.secret.length<32)throw Error('Konfigurasi APP_SECRET belum tersedia.');const payload=Buffer.from(JSON.stringify({...data,purpose,exp:Math.floor(Date.now()/1000)+seconds,nonce:randomBytes(12).toString('hex')})).toString('base64url');return payload+'.'+createHmac('sha256',config.secret).update(payload).digest('base64url');}
export function verifyToken(config,token,purpose){try{if(config.secret.length<32||typeof token!=='string'||token.length>14000)throw Error();const [payload,sig,...rest]=token.split('.');if(rest.length||!sig||!equal(sig,createHmac('sha256',config.secret).update(payload).digest('base64url')))throw Error();const data=JSON.parse(Buffer.from(payload,'base64url').toString());if(data.purpose!==purpose||!Number.isSafeInteger(data.exp)||data.exp<=Math.floor(Date.now()/1000))throw Error();return data;}catch{throw Error('Sesi berakhir atau tiket tidak valid. Muat ulang dan coba lagi.');}}
export function passwordMatches(expected,actual,secret){const salt=hash('password:'+secret);return equal(scryptSync(String(actual||''),salt,32),scryptSync(String(expected||''),salt,32));}
export function requireTechnician(config,pin){if(config.technicianPin&&!passwordMatches(config.technicianPin,pin,config.secret))throw Error('PIN teknisi tidak sesuai.');}
export function cookieValue(req,name){const raw=String(req.headers.cookie||'').split(';').find(p=>p.trim().startsWith(name+'='));return raw?raw.trim().slice(name.length+1):'';}
export function adminSession(config,req){const session=verifyToken(config,cookieValue(req,'wi_admin_session'),'admin');if(config.adminPassword.length<12||!equal(session.version,hash(config.adminPassword)))throw Error('Sesi admin berakhir. Silakan masuk kembali.');return session;}
export function sessionCookie(config,token,maxAge=3600){return 'wi_admin_session='+token+'; Path=/api; HttpOnly; SameSite=Strict; Max-Age='+maxAge+(config.production?'; Secure':'');}
export function validOrigin(config,req){const supplied=req.headers.origin;if(!supplied)return false;try{const origin=new URL(supplied).origin;const allowed=[config.origin,config.vercelHost?'https://'+config.vercelHost:''].filter(Boolean).map(v=>new URL(v).origin);if(!allowed.length&&!config.production)allowed.push('http://localhost:4173','http://127.0.0.1:4173');return allowed.includes(origin);}catch{return false;}}
