import {randomBytes} from 'node:crypto';
import {requireStorage} from './config.js';
const API='https://www.googleapis.com/drive/v3/';
const fields='id,name,mimeType,parents,size,md5Checksum,capabilities';
export class GoogleDrive {
 constructor(config,fetchImpl=fetch){this.config=config;this.fetch=fetchImpl;this.access=null;}
 async token(){requireStorage(this.config);if(this.access&&this.access.until>Date.now()+60000)return this.access.value;const c=this.config;const res=await this.fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:c.clientId,client_secret:c.clientSecret,refresh_token:c.refreshToken,grant_type:'refresh_token'}),signal:AbortSignal.timeout(25000)});const data=await res.json();if(!res.ok||!data.access_token)throw Error('Otorisasi Drive tidak aktif. Administrator perlu memperbarui koneksi Google.');this.access={value:data.access_token,until:Date.now()+Number(data.expires_in||3600)*1000};return data.access_token;}
 async request(url,init={},retry=true){const token=await this.token();const res=await this.fetch(url,{...init,headers:{...init.headers,authorization:'Bearer '+token},signal:AbortSignal.timeout(45000)});if(res.status===401&&retry){this.access=null;return this.request(url,init,false);}if(!res.ok){let data={};try{data=await res.json();}catch{}const reason=data.error?.errors?.[0]?.reason;const error=Error(res.status===404?'File atau folder Drive tidak ditemukan.':res.status===409?'ID file sudah digunakan.':reason==='storageQuotaExceeded'?'Kuota penyimpanan Drive penuh.':'Drive belum dapat memproses permintaan. Coba lagi.');error.status=res.status;throw error;}return res;}
 async generateIds(count){const res=await this.request(API+'files/generateIds?'+new URLSearchParams({count:String(count),space:'drive',type:'files'}));const data=await res.json();if(data.ids?.length!==count)throw Error('Alokasi file Drive belum lengkap. Coba lagi.');return data.ids;}
 async get(id){return (await this.request(API+'files/'+encodeURIComponent(id)+'?'+new URLSearchParams({fields,supportsAllDrives:'true'}))).json();}
 async list({parent,name,mimeType,pageToken,pageSize=30}){const escaped=v=>String(v).replace(/\\/g,'\\\\').replace(/'/g,"\\'");let q="'"+escaped(parent)+"' in parents and trashed = false";if(name)q+=" and name = '"+escaped(name)+"'";if(mimeType)q+=" and mimeType = '"+escaped(mimeType)+"'";const params=new URLSearchParams({q,pageSize:String(pageSize),fields:'nextPageToken,files('+fields+')',supportsAllDrives:'true',includeItemsFromAllDrives:'true'});if(pageToken)params.set('pageToken',pageToken);return (await this.request(API+'files?'+params)).json();}
 async createFile({id,name,parent,mimeType,body}){const meta={id,name,mimeType,parents:[parent]};if(mimeType==='application/vnd.google-apps.folder')return (await this.request(API+'files?'+new URLSearchParams({fields,supportsAllDrives:'true'}),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(meta)})).json();const boundary='weekly_'+randomBytes(16).toString('hex');const bytes=Buffer.from(body||'');const payload=Buffer.concat([Buffer.from('--'+boundary+'\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n'+JSON.stringify(meta)+'\r\n--'+boundary+'\r\nContent-Type: '+mimeType+'\r\n\r\n'),bytes,Buffer.from('\r\n--'+boundary+'--\r\n')]);const url='https://www.googleapis.com/upload/drive/v3/files?'+new URLSearchParams({uploadType:'multipart',fields,supportsAllDrives:'true'});return (await this.request(url,{method:'POST',headers:{'content-type':'multipart/related; boundary='+boundary},body:payload})).json();}
 async download(id,limit){const res=await this.request(API+'files/'+encodeURIComponent(id)+'?alt=media&supportsAllDrives=true');if(Number(res.headers.get('content-length')||0)>limit)throw Error('File Drive melebihi batas ukuran.');const reader=res.body.getReader(),chunks=[];let size=0;try{while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>limit)throw Error('File Drive melebihi batas ukuran.');chunks.push(Buffer.from(value));}}finally{await reader.cancel();}return Buffer.concat(chunks);}
}
