import {schema,reportSchema,validate,activeField,csv,validDate} from './domain.js';
import {hash,equal,signToken,verifyToken} from './auth.js';
const FOLDER='application/vnd.google-apps.folder',MAX_PHOTO=1000000,MAX_TOTAL=8000000;
const REGISTRY=/^radar-registry-([A-Z0-9][A-Z0-9 ._-]{1,23})\.json$/,MAX_RADARS=100;
export function normalizeRadarId(value){const id=String(value??'').trim().replace(/\s+/g,' ').toUpperCase();if(id==='LAINNYA'||!/^[A-Z0-9][A-Z0-9 ._-]{1,23}$/.test(id))throw Error('ID radar 2–24 karakter: huruf, angka, spasi, titik, garis bawah, atau strip.');return id;}
const fileId=id=>typeof id==='string'&&/^[A-Za-z0-9_-]{10,128}$/.test(id);
const uuid=id=>typeof id==='string'&&/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/.test(id);
export function decodePhoto(p){if(!p||typeof p.data!=='string'||p.data.length>1333336||p.data.length%4||!/^[A-Za-z0-9+/]*={0,2}$/.test(p.data))throw Error('Foto tidak valid atau melebihi 1 MB.');const bytes=Buffer.from(p.data,'base64'),jpeg=bytes[0]===255&&bytes[1]===216&&bytes[2]===255,png=bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])),webp=bytes.subarray(0,4).toString()==='RIFF'&&bytes.subarray(8,12).toString()==='WEBP';const type=jpeg?'image/jpeg':png?'image/png':webp?'image/webp':'';if(!type||p.type!==type||bytes.length>MAX_PHOTO||bytes.toString('base64')!==p.data)throw Error('Gunakan foto JPEG, PNG, atau WebP maksimal 1 MB.');return {bytes,type,ext:jpeg?'jpg':png?'png':'webp'};}
function prepare(p,extra){schema(p.type);if(typeof p.receiptKey!=='string'||!/^[a-f0-9]{64}$/.test(p.receiptKey))throw Error('Kunci pengiriman tidak valid.');if(JSON.stringify(p.answers||{}).length>100000)throw Error('Jawaban terlalu panjang.');if(!Array.isArray(p.photos)||p.photos.length>7)throw Error('Jumlah foto tidak valid.');const seen=new Set(),spec=schema(p.type),photos=[];for(const photo of p.photos){const f=spec.fields.find(f=>f.name===photo.field&&f.type==='Image');if(!f||seen.has(f.name))throw Error('Kolom foto tidak valid atau berulang.');seen.add(f.name);if(!activeField(f,p.answers))continue;if(!['image/jpeg','image/png','image/webp'].includes(photo.type)||!Number.isSafeInteger(photo.size)||photo.size<3||photo.size>MAX_PHOTO||!/^[a-f0-9]{64}$/.test(photo.digest))throw Error('Metadata foto tidak valid.');photos.push({field:photo.field,type:photo.type,size:photo.size,digest:photo.digest});}if(photos.reduce((n,p)=>n+p.size,0)>MAX_TOTAL)throw Error('Total foto melebihi 8 MB.');const checked=validate(p.type,p.answers,photos.map(p=>p.field),extra);if(checked.errors.length){const e=Error('Lengkapi kolom yang ditandai.');e.errors=checked.errors;throw e;}photos.sort((a,b)=>a.field.localeCompare(b.field));return {answers:checked.answers,photos,receiptHash:hash(p.receiptKey),fingerprint:hash(JSON.stringify({type:p.type,answers:checked.answers,photos}))};}
export function publicRecord(r){return {id:r.id,type:r.type,model:r.model,answers:r.answers,fields:reportSchema(r.type,r.answers,Object.keys(r.photos)).fields,photos:Object.entries(r.photos).map(([field,p])=>({field,name:p.name,type:p.type})),savedAt:r.savedAt};}
export function summary(r){const a=r.answers,fields=reportSchema(r.type,r.answers).fields.filter(f=>f.type==='Enum'&&(f.options.includes('Baik')||f.name.endsWith('_Section_Status'))),bad=fields.some(f=>a[f.name]==='Ada masalah'),skipped=fields.some(f=>a[f.name]==='Tidak diperiksa');return {id:r.id,type:r.type,unit:r.type==='RADAR'?(a.Radar_ID==='Lainnya'?a.Radar_ID_Other:a.Radar_ID):a.RTS_ID,location:a.Radar_Location||a.RTS_Location,name:a.Technician_Name,date:a.Inspection_DateTime,status:bad?'Ada masalah':skipped?'Belum lengkap':'Tidak ada masalah dilaporkan',savedAt:r.savedAt};}
export function createInspectionService({drive,config}){
 const ticket=t=>{const a=verifyToken(config,t,'upload');if(!fileId(a.id)||a.parent!==config.folderIds[a.type]||!a.ids||!Array.isArray(a.photos))throw Error('Tiket upload tidak sesuai folder.');return a;};
 const fileInside=async(id,parent,name,mime)=>{const f=await drive.get(id);if(!f.parents?.includes(parent)||name&&f.name!==name||mime&&f.mimeType!==mime)throw Error('File harus berada di dalam folder laporan ini.');return f;};
 const named=async(parent,name)=>{const result=await drive.list({parent,name,pageSize:2});if(result.files.length>1)throw Error('Nama file laporan berulang. Periksa folder di Drive.');return result.files[0]||null;};
 const json=async file=>JSON.parse((await drive.download(file.id,200000)).toString('utf8'));
 async function createOnce(input){try{return await drive.createFile(input);}catch(e){if(e.status!==409)throw e;const f=await fileInside(input.id,input.parent,input.name,input.mimeType);if(input.mimeType!==FOLDER){const actual=await drive.download(input.id,Math.max(200000,Buffer.byteLength(input.body||'')));if(!actual.equals(Buffer.from(input.body||'')))throw Error('ID file sudah digunakan dengan isi berbeda. Buat inspeksi baru.');}return f;}}
 async function registeredRadars(){const known=schema('RADAR').fields.find(f=>f.name==='Radar_ID').options.map(o=>o.toUpperCase()),ids=[];let pageToken;for(let page=0;page<5;page++){const result=await drive.list({parent:config.folderIds.RADAR,mimeType:'application/json',pageSize:200,pageToken});for(const f of result.files){const m=REGISTRY.exec(f.name);if(m&&!ids.includes(m[1])&&!known.includes(m[1]))ids.push(m[1]);}pageToken=result.nextPageToken;if(!pageToken)break;}return ids.sort((a,b)=>a.localeCompare(b,'en',{numeric:true}));}
 async function radarOptions(p){const id=p.type==='RADAR'&&typeof p.answers?.Radar_ID==='string'?p.answers.Radar_ID.trim():'';return id&&!schema('RADAR').fields.find(f=>f.name==='Radar_ID').options.includes(id)?{Radar_ID:await registeredRadars()}:undefined;}
 async function verifyFolders(type){const root=await drive.get(config.rootFolderId),f=await drive.get(config.folderIds[type]);if(root.mimeType!==FOLDER||f.mimeType!==FOLDER||!f.parents?.includes(root.id)||f.capabilities?.canAddChildren===false)throw Error('Folder peralatan harus berada di dalam folder tujuan dan dapat ditulis.');}
 async function pending(a){await fileInside(a.id,a.parent,a.id,FOLDER);const f=await fileInside(a.ids.pending,a.id,'pending.json','application/json'),p=await json(f),photos=a.photos.map(({field,type,size,digest})=>({field,type,size,digest})),actual=hash(JSON.stringify({type:a.type,answers:p.answers,photos}));if(!equal(p.fingerprint,a.fingerprint)||!equal(actual,a.fingerprint)||!equal(p.receiptHash,a.receiptHash)||JSON.stringify(p.photos)!==JSON.stringify(a.photos))throw Error('Isi pengiriman berubah setelah proses dimulai. Gunakan inspeksi baru.');return p;}
 async function reportFolder(type,id){schema(type);if(!fileId(id))throw Error('ID inspeksi tidak valid.');let f;try{f=await drive.get(id);}catch(e){if(e.status!==404||!uuid(id))throw e;f=(await drive.list({parent:config.folderIds[type],name:id,mimeType:FOLDER,pageSize:2})).files[0];}if(!f||f.mimeType!==FOLDER||!f.parents.includes(config.folderIds[type]))throw Error('Folder laporan tidak sesuai jenis peralatan.');return f;}
 async function readRecord(folder){const file=await named(folder.id,'inspection.json');if(!file)return null;const r=await json(file);if(r.schemaVersion!==1||r.id!==folder.name||!r.answers||!r.photos||!config.folderIds[r.type])throw Error('Format laporan tidak dikenali.');return r;}
 async function authorized(request,admin=false){const folder=await reportFolder(request.type,request.id),r=await readRecord(folder);if(!r||r.type!==request.type)throw Error('Laporan tidak ditemukan.');if(!admin&&(typeof request.key!=='string'||!equal(r.receiptHash,hash(request.key))))throw Error('Kunci laporan tidak sesuai.');return {folder,r};}
 return {
  async allocate(p){const prepared=prepare(p,await radarOptions(p));await verifyFolders(p.type);const ids=await drive.generateIds(prepared.photos.length+4);const data={id:ids[0],parent:config.folderIds[p.type],type:p.type,receiptHash:prepared.receiptHash,fingerprint:prepared.fingerprint,ids:{pending:ids[1],csv:ids[2],record:ids[3]},photos:prepared.photos.map((photo,i)=>({...photo,id:ids[i+4]}))};return {ok:true,id:data.id,type:p.type,uploadTicket:signToken(config,'upload',data,86400)};},
  async begin(p){const a=ticket(p.uploadTicket),prepared=prepare(p,await radarOptions(p));if(p.type!==a.type||!equal(prepared.fingerprint,a.fingerprint)||!equal(prepared.receiptHash,a.receiptHash))throw Error('Isi pengiriman berubah atau kunci tidak sesuai. Mulai inspeksi baru.');await verifyFolders(a.type);await createOnce({id:a.id,name:a.id,parent:a.parent,mimeType:FOLDER});const data={fingerprint:a.fingerprint,receiptHash:a.receiptHash,answers:prepared.answers,photos:a.photos};await createOnce({id:a.ids.pending,name:'pending.json',parent:a.id,mimeType:'application/json',body:JSON.stringify(data)});return {ok:true,id:a.id};},
  async photo(p){const a=ticket(p.uploadTicket);await pending(a);const expected=a.photos.find(photo=>photo.field===p.field);if(!expected)throw Error('Kolom foto tidak valid.');const decoded=decodePhoto(p);if(decoded.type!==expected.type||decoded.bytes.length!==expected.size||!equal(hash(decoded.bytes),expected.digest))throw Error('Foto berubah atau tidak sesuai alokasi. Mulai inspeksi baru.');await createOnce({id:expected.id,name:p.field+'.'+decoded.ext,parent:a.id,mimeType:decoded.type,body:decoded.bytes});return {ok:true,field:p.field};},
  async commit(p){const a=ticket(p.uploadTicket),intent=await pending(a),answers={...intent.answers,Inspection_ID:a.id},photos={};for(const photo of a.photos){const ext=photo.type==='image/jpeg'?'jpg':photo.type==='image/png'?'png':'webp',name=photo.field+'.'+ext;let file;try{file=await fileInside(photo.id,a.id,name,photo.type);}catch(e){if(e.status===404)throw Error('Lengkapi foto sebelum mengirim laporan.');throw e;}const bytes=await drive.download(file.id,MAX_PHOTO);decodePhoto({type:photo.type,data:bytes.toString('base64')});if(bytes.length!==photo.size||!equal(hash(bytes),photo.digest))throw Error('Foto tidak sesuai transaksi.');photos[photo.field]={id:photo.id,name,type:photo.type,size:bytes.length,digest:photo.digest};answers[photo.field]=a.type+'/'+a.id+'/'+name;}
   await createOnce({id:a.ids.csv,name:'inspection.csv',parent:a.id,mimeType:'text/csv',body:'\uFEFF'+csv(a.type,answers)});
   const expected={schemaVersion:1,id:a.id,type:a.type,model:schema(a.type).model,answers,photos,receiptHash:a.receiptHash,fingerprint:a.fingerprint},matches=saved=>Object.keys(expected).every(key=>JSON.stringify(saved[key])===JSON.stringify(expected[key]));
   let existing;try{existing=await json(await fileInside(a.ids.record,a.id,'inspection.json','application/json'));}catch(e){if(e.status!==404)throw e;}
   if(existing){if(!matches(existing))throw Error('Laporan sudah menggunakan isi berbeda.');return {ok:true,id:a.id,type:a.type,savedAt:existing.savedAt,duplicate:true};}
   const r={...expected,savedAt:new Date().toISOString()};try{await drive.createFile({id:a.ids.record,name:'inspection.json',parent:a.id,mimeType:'application/json',body:JSON.stringify(r,null,2)});}catch(e){if(e.status!==409)throw e;const saved=await json(await fileInside(a.ids.record,a.id,'inspection.json','application/json'));if(!matches(saved))throw Error('Laporan sudah menggunakan isi berbeda.');return {ok:true,id:a.id,type:a.type,savedAt:saved.savedAt,duplicate:true};}return {ok:true,id:a.id,type:a.type,savedAt:r.savedAt};},
  async read(p,admin=false){const {r}=await authorized(p,admin);return {ok:true,record:publicRecord(r),csv:csv(r.type,r.answers,reportSchema(r.type,r.answers,Object.keys(r.photos)).fields)};},
  async readPhoto(p,admin=false){const {r,folder}=await authorized(p,admin),photo=r.photos[p.field],field=reportSchema(p.type,r.answers,Object.keys(r.photos)).fields.find(f=>f.name===p.field&&f.type==='Image');if(!field||!photo||!new RegExp('^'+field.name+'\\.(jpg|png|webp)$').test(photo.name))throw Error('Foto tidak ditemukan.');const f=await fileInside(photo.id,folder.id,photo.name,photo.type);if(Number(f.size)>MAX_PHOTO)throw Error('Foto melebihi 1 MB.');const bytes=await drive.download(f.id,MAX_PHOTO);decodePhoto({type:photo.type,data:bytes.toString('base64')});if(photo.digest&&(bytes.length!==photo.size||!equal(hash(bytes),photo.digest)))throw Error('Foto berubah atau tidak sesuai laporan tersimpan.');return {ok:true,name:photo.name,type:photo.type,data:bytes.toString('base64')};},
  async list(p){schema(p.type);const from=p.from||'',to=p.to||'';if(from&&!validDate(from,false)||to&&!validDate(to,false)||from&&to&&from>to)throw Error('Rentang tanggal tidak valid.');const filterHash=hash(JSON.stringify({type:p.type,from,to,unit:p.unit||'',status:p.status||''}));let pageToken;if(p.cursor){const cursor=verifyToken(config,p.cursor,'cursor');if(cursor.filterHash!==filterHash)throw Error('Filter berubah. Muat riwayat dari awal.');pageToken=cursor.pageToken;}const result=await drive.list({parent:config.folderIds[p.type],mimeType:FOLDER,pageSize:30,pageToken}),items=[];let skipped=0;for(const folder of result.files){try{const r=await readRecord(folder);if(!r)continue;if(r.type!==p.type)throw Error();const s=summary(r),date=s.date.slice(0,10);if(from&&date<from||to&&date>to||p.unit&&!String(s.unit).toLowerCase().includes(String(p.unit).toLowerCase())||p.status&&s.status!==p.status)continue;items.push(s);}catch{skipped++;}}items.sort((a,b)=>b.date.localeCompare(a.date));return {ok:true,items,skipped,nextCursor:result.nextPageToken?signToken(config,'cursor',{pageToken:result.nextPageToken,filterHash},3600):null};},
  async radars(){return {ok:true,radars:await registeredRadars()};},
  async addRadar(p){const id=normalizeRadarId(p.id);await verifyFolders('RADAR');const list=await registeredRadars(),known=schema('RADAR').fields.find(f=>f.name==='Radar_ID').options.filter(o=>o!=='Lainnya'),match=[...known,...list].find(o=>o.toUpperCase()===id);if(match)return {ok:true,id:match,existing:true,radars:list};if(list.length>=MAX_RADARS)throw Error('Daftar radar sudah penuh. Hubungi administrator.');const [fid]=await drive.generateIds(1);await createOnce({id:fid,name:'radar-registry-'+id+'.json',parent:config.folderIds.RADAR,mimeType:'application/json',body:JSON.stringify({schemaVersion:1,id,addedAt:new Date().toISOString()})});return {ok:true,id,existing:false,radars:[...list,id].sort((a,b)=>a.localeCompare(b,'en',{numeric:true}))};},
  async checkStorage(){await verifyFolders('RADAR');await verifyFolders('RTS');return {ok:true,folders:config.folderIds};}
 };
}
